class Player extends Block{
    constructor(x,y,w,h,world){
        super(x,y,w,h,world);
        this.body.SetFixedRotation(true);
        this.body.SetLinearDamping(3);
        this.keyUp=false;
        this.keyDown=false;
        this.keyLeft=false;
        this.keyRight=false;
    }
    update(){
        let v=this.body.GetLinearVelocity();
        if(this.keyUp){
            v.y-=1;
            v.y=v.y<-5?-5:v.y;
        }
        if(this.keyDown){
            v.y+=1;
            v.y=v.y>5?5:v.y;
        }
        if(this.keyLeft){
            v.x-=1;
            v.x=v.x<-5?-5:v.x;
        }
        if(this.keyRight){
            v.x+=1;
            v.x=v.x>5?5:v.x;
        }
        this.body.SetLinearVelocity(v);
    }
    draw(context){
        super.draw(context);
    }
}